clc;
clear all;
syms k L3 a S
M_L3 = [cos(k*L3),-1i*a*sin(k*L3)/S;...
    -1i*S*sin(k*L3)/a,cos(k*L3)];
syms l Lv2 S2
M_V2 = [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)]...
    * ...
    [cos(k*Lv2),-1i*a*sin(k*Lv2)/S2;...
    -1i*S2*sin(k*Lv2)/a,cos(k*Lv2)]...
    *...
    [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)];
M_V2 = simplify(M_V2);
syms L2
M_L2 = [cos(k*L2),-1i*a*sin(k*L2)/S;...
    -1i*S*sin(k*L2)/a,cos(k*L2)];
syms Lv1 S1
M_V1 = [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)]...
    * ...
    [cos(k*Lv1),-1i*a*sin(k*Lv1)/S1;...
    -1i*S1*sin(k*Lv1)/a,cos(k*Lv1)]...
    *...
    [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)];
M_V1 = simplify(M_V1);
syms L1
M_L1 = [cos(k*L1),-1i*a*sin(k*L1)/S;...
    -1i*S*sin(k*L1)/a,cos(k*L1)];
M_total = M_L3 * M_V2 * M_L2 * M_V1 * M_L1; 

M_total = simple(M_total)
pretty(M_total)