clc;
clear all;
syms k L3 a S
frequency = 10;
a = 345;
oumiga = 2.*frequency.*pi;
k = oumiga./a;
Dpipe = 0.157;%管道直径（m）
S = pi*Dpipe^2/4;

M_L3 = [cos(k*L3),-1i*a*sin(k*L3)/S;...
    -1i*S*sin(k*L3)/a,cos(k*L3)];
 M_L3 %= simplify(M_L3)
syms l Lv Sv
Dv = 0.5;%缓冲罐的直径（m）
Lv = 1;%缓冲罐长度
l = 0.115;%缓冲罐封头长度
Sv = pi*Dv^2/4;
M_V2 = [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)]...
    * ...
    [cos(k*Lv),-1i*a*sin(k*Lv)/Sv;...
    -1i*Sv*sin(k*Lv)/a,cos(k*Lv)]...
    *...
    [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)];
syms L2
M_L2 = [cos(k*L2),-1i*a*sin(k*L2)/S;...
    -1i*S*sin(k*L2)/a,cos(k*L2)];

M_V1 = [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)]...
    * ...
    [cos(k*Lv),-1i*a*sin(k*Lv)/Sv;...
    -1i*Sv*sin(k*Lv)/a,cos(k*Lv)]...
    *...
    [cos(k*l),-1i*a*sin(k*l)/S;...
    -1i*S*sin(k*l)/a,cos(k*l)];

syms L1
L1 = 1;
M_L1 = [cos(k*L1),-1i*a*sin(k*L1)/S;...
    -1i*S*sin(k*L1)/a,cos(k*L1)];

M_total = M_L3 * M_V2 * M_L2 * M_V1 * M_L1; 

M_total = simple(M_total)
pretty(M_total)